env: DEV
port: 1234
logLevel: DEBUG
logFormat: text
logMode: true
postgres:
  connectTimeout: 10
  maxIdleConnections: 10
  maxOpenConnections: 20
  dbName: test_cache_cqrs
  host: localhost
  password: postgres
  port: 5432
  schema: public
  user: postgres
redis:
  host: localhost
  password:
  db: 0
  port: 6379
  keySubmitSosialisasiTtl: 5m
  valueSubmitSosialisasiTtl: 30m
rate: 1
interval: second
