version: "3.8"

services:
  redis:
    image: redis:6.0.9-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - web_api

  postgesql:
    image: postgres:12-alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_cache_cqrs
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - web_api

  web:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    environment:
      - PORT=5000
    depends_on:
      - redis
      - postgesql
    restart: always
    volumes:
      - ./:/app
    networks:
      - web_api

networks:
  web_api:
    driver: bridge